language: python
python:
  - "3.5"
cache: pip
install: 
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-tests
branches:
  only:
  - user-register-160784779
after_success:
  - coveralls