language: python
python:
  - "3.5"
cache: pip
env:
  global:
    - CODECOV_TOKEN="eaca997e-b9c7-4324-bf68-dfc2dc8addf5"
install: 
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-tests
after_success:
  - coveralls